package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static com.codeborne.selenide.Selenide.open;
import static com.codeborne.selenide.Selenide.title;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;


public class GeneratedTests extends TestBase {
    @Test
    @Description("Soon to be implemented by you (or QA.GURU engineers)")
    @DisplayName("Проверка что есть надпись на главное странице")
    void generatedTest() {
        step("Открыть https://vr-arsoft.com/ru_RU/", () -> {
            step("// todo: just add selenium action");
        });

        step("Проверить что есть надпись \"Система 3D-проектирования в дополненной реальности.\"", () -> {
            step("// todo: just add selenium action");
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page title should have header text")
    void titleTest() {
        step("Open url 'https://vr-arsoft.com/ru_RU/'", () ->
            open("https://vr-arsoft.com/ru_RU/"));

        step("Page title should have text 'ООО «АР СОФТ»'", () -> {
            String expectedTitle = "ООО «АР СОФТ»";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://vr-arsoft.com/ru_RU/'", () ->
            open("https://vr-arsoft.com/ru_RU/"));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}